In [1]:
import pandas as pd
import os

In [2]:
def load_data(file_path):
    df = pd.read_csv(file_path ,encoding='gbk')
    columns = df.columns
    df.fillna(df.mean(numeric_only=True) ,inplace=True)
    return df

In [3]:
file_path = '../temp/final'

#生成路径
lai_path = os.path.join(file_path, 'lai', 'final.csv')
li_path = os.path.join(file_path, 'li', 'final.csv')
chen_path = os.path.join(file_path, 'chen', 'final.csv')
lu_path = os.path.join(file_path, 'lu', 'final.csv')
zheng_path = os.path.join(file_path, 'zheng', 'final.csv')

lai = load_data(lai_path)
li = load_data(li_path)
lu = load_data(lu_path)
chen = load_data(chen_path)
zheng = load_data(zheng_path)

In [4]:
df = pd.concat([lai, li, lu, chen, zheng], copy= True)
df

,交易额,商户名称,交易日期,交易时间,星期,节假日,气温,气象站大气压,海平面大气压,相对湿度,平均风速,特殊天象,时间戳,饭点课程_早,饭点课程_午,饭点课程_晚
0,11.84,美食林小猪憨尼麻辣烫,2023-04-25,17:35,2,0,2,744.0,756.9,100,3,0,1.682415e+09,1,1,1
1,13.00,美食林川蜀源烤鱼,2023-04-25,11:46,2,0,7,742.7,755.4,66,10,0,1.682394e+09,1,1,1
2,2.65,学苑食堂副食一组,2023-04-25,7:49,2,0,12,742.1,754.6,33,5,0,1.682380e+09,1,1,1
3,18.40,紫丁香餐吧机器人收银组,2023-04-24,17:57,1,0,13,750.2,762.8,16,3,0,1.682330e+09,1,1,0
4,18.40,紫丁香餐吧机器人收银组,2023-04-24,11:27,1,0,14,754.7,767.3,14,6,0,1.682307e+09,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,8.00,学苑食堂副食三组,2022-07-04,17:05,1,0,27,740.5,752.3,79,4,0,1.656926e+09,0,0,0
415,14.28,学子副食一组,2022-07-04,11:55,1,0,27,741.3,753.1,74,4,0,1.656907e+09,0,0,0
416,9.60,一区饺子园主食一组,2022-07-03,17:05,7,1,28,740.5,752.3,66,6,0,1.656839e+09,0,0,0
417,7.00,学苑食堂主食三组（面条）,2022-07-03,11:34,7,1,28,742.1,753.9,70,6,0,1.656819e+09,0,0,0
418,3.70,学苑食堂副食一组,2022-07-03,8:16,7,1,24,742.6,754.6,83,5,0,1.656807e+09,0,0,0

In [7]:
df['商户编号'] = pd.factorize(df['商户名称'])[0]

# 创建映射关系DataFrame
mapping_df = pd.DataFrame({
    '商户名称': df['商户名称'].unique(),
    '商户编号': df['商户编号'].unique()
})


# 将映射关系保存为CSV文件
mapping_df.to_csv('map.csv', sep= ',', encoding='gbk', index=False)

In [45]:
column_mapping = {
    '交易额': 'amount',
    '商户名称': 'merchant_name',
    '交易日期': 'date',
    '交易时间': 'time',
    '星期': 'weekday',
    '节假日': 'holiday',
    '气温': 'temperature',
    '气象站大气压': 'station_pressure',
    '海平面大气压': 'sea_level_pressure',
    '相对湿度': 'relative_humidity',
    '平均风速': 'windspeed',
    '特殊天象': 'special_weather',
    '时间戳': 'timestamp',
    '饭点课程_早': 'meal_course_breakfast',
    '饭点课程_午': 'meal_course_lunch',
    '饭点课程_晚': 'meal_course_dinner',
    '商户编号': 'merchant_code'
}

# 使用rename()方法重命名DataFrame的列
df.rename(columns=column_mapping, inplace=True)

In [46]:
lai = df[:471]
li = df[471:758]
lu = df[758:1088]
chen = df[1088:1383]
zheng = df[1383:]

In [52]:
def save_data(data, id):
    save_path = os.path.join(file_path, id, 'final(english).csv')
    data.to_csv(save_path,sep= ',', encoding='gbk',index=False)

save_data(lai, 'lai')
save_data(li, 'li')
save_data(lu, 'lu')
save_data(chen, 'chen')
save_data(zheng, 'zheng')