In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def load_data(file_name):
    df = pd.read_csv("D:/Innovation/DataSet/" + file_name ,encoding='gbk')
    columns = df.columns
    df.fillna(df.mean(numeric_only=True) ,inplace=True)
    return df

In [2]:
df = load_data('混合数据.csv')
df

,学工号,交易额,商户名称,交易日期,星期,是否为工作日,气温,气象站大气压,海平面大气压,相对湿度,平均风速,交易时间
0,2021****86,8.90,淘乐学苑水果,2023/4/25,星期二,1,7,742.7,755.4,66,10,18:02
1,2021****86,11.84,美食林小猪憨尼麻辣烫,2023/4/25,星期二,1,7,742.7,755.4,66,10,17:35
2,2021****86,13.00,美食林川蜀源烤鱼,2023/4/25,星期二,1,7,742.7,755.4,66,10,11:46
3,2021****86,2.65,学苑食堂副食一组,2023/4/25,星期二,1,7,742.7,755.4,66,10,7:49
4,2021****86,18.40,紫丁香餐吧机器人收银组,2023/4/24,星期一,1,14,754.0,766.6,14,7,17:57
...,...,...,...,...,...,...,...,...,...,...,...,...
1391,2021****86,14.00,民族二餐厅自助榆林镇筋饼,2022/1/1,星期六,0,-17,753.2,767.3,60,4,11:22
1392,2021****86,0.19,B02公寓浴池,2022/1/1,星期六,0,-17,753.2,767.3,60,4,2:04
1393,2021****86,0.17,B02公寓浴池,2022/1/1,星期六,0,-17,753.2,767.3,60,4,2:04
1394,2021****86,0.09,B02公寓浴池,2022/1/1,星期六,0,-17,753.2,767.3,60,4,2:03
1395,2021****86,0.01,B02公寓浴池,2022/1/1,星期六,0,-17,753.2,767.3,60,4,2:03

In [5]:
week = []

for w in df['星期']:
    if w == '星期一':
        week.append(1)
    if w == '星期二':
        week.append(2)
    if w == '星期三':
        week.append(3)
    if w == '星期四':
        week.append(4)
    if w == '星期五':
        week.append(5)
    if w == '星期六':
        week.append(6)
    if w == '星期日':
        week.append(7)
        
week

[2,
 2,
 2,
 2,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 6,
 5,
 5,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 6,
 6,
 6,
 6,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 6,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 4,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 7,
 6,
 5,
 5,
 5,
 ...]

In [6]:
df['星期'] = week
df

,学工号,交易额,商户名称,交易日期,星期,是否为工作日,气温,气象站大气压,海平面大气压,相对湿度,平均风速,交易时间
0,2021****86,8.90,淘乐学苑水果,2023/4/25,2,1,7,742.7,755.4,66,10,18:02
1,2021****86,11.84,美食林小猪憨尼麻辣烫,2023/4/25,2,1,7,742.7,755.4,66,10,17:35
2,2021****86,13.00,美食林川蜀源烤鱼,2023/4/25,2,1,7,742.7,755.4,66,10,11:46
3,2021****86,2.65,学苑食堂副食一组,2023/4/25,2,1,7,742.7,755.4,66,10,7:49
4,2021****86,18.40,紫丁香餐吧机器人收银组,2023/4/24,1,1,14,754.0,766.6,14,7,17:57
...,...,...,...,...,...,...,...,...,...,...,...,...
1391,2021****86,14.00,民族二餐厅自助榆林镇筋饼,2022/1/1,6,0,-17,753.2,767.3,60,4,11:22
1392,2021****86,0.19,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:04
1393,2021****86,0.17,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:04
1394,2021****86,0.09,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:03
1395,2021****86,0.01,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:03

In [7]:
time = df['交易时间']

0       18:02
1       17:35
2       11:46
3        7:49
4       17:57
        ...
1391    11:22
1392     2:04
1393     2:04
1394     2:03
1395     2:03
Name: 交易时间, Length: 1396, dtype: object

In [8]:
import datetime

In [41]:
int(datetime.datetime.strptime(time[2], "%H:%M").strftime("%H"))

11

In [50]:
period = []

for t in time:
    T = int(datetime.datetime.strptime(t, "%H:%M").strftime("%H"))
    if  T >= 6 and T < 10:   #morning
        period.append(0)
    if T >= 10 and T < 13:   #noon
        period.append(1)
    if T >= 13 and T < 17:   #afternoon
        period.append(2)
    if T >= 17 and T < 19:   #evening
        period.append(3)
    if T >= 19 or T < 6:    #night
        period.append(4)
        
period

[3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 0,
 3,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 1,
 1,
 0,
 1,
 0,
 3,
 3,
 1,
 0,
 1,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 2,
 2,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 1,
 1,
 0,
 3,
 3,
 1,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 0,
 1,
 0,
 3,
 3,
 2,
 0,
 2,
 1,
 0,
 2,
 2,
 1,
 1,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 1,
 0,
 1,
 0,
 3,
 3,
 1,
 0,
 1,
 0,
 3,
 1,
 2,
 2,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 0,
 3,
 3,
 1,
 0,
 1,
 0,
 3,
 3,
 1,
 1,
 0,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 1,
 0,
 3,
 2,
 0,
 3,
 3,
 0,
 3,
 1,
 0,
 3,
 1,
 1,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 1,
 1,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 0,
 3,
 2,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 2,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 2,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 1,
 0,
 3,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 0,
 3,
 3,
 1,
 0,
 0,
 3,
 3,
 1,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 0,
 3,
 3,
 1,
 3,
 3,
 1,
 0,
 3,
 1,
 1,
 3,
 3,
 3,
 1,
 3,
 3,
 1,
 1,
 3,
 1,
 1,
 3,
 3,
 1,
 2,
 1,
 0,
 3,
 3,
 1,
 1,
 3,
 3,
 1,
 1,
 3,
 1,
 3,
 3,
 1,
 3,
 1,
 3,
 3,
 1,
 1,
 0,
 0,
 3,
 3,
 0,
 3,
 3,
 1,
 1,
 3,
 3,
 3,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 3,
 3,
 1,
 0,
 3,
 3,
 0,
 0,
 2,
 0,
 4,
 4,
 4,
 4,
 4,
 3,
 1,
 1,
 0,
 0,
 4,
 4,
 4,
 4,
 1,
 1,
 1,
 0,
 0,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 0,
 0,
 4,
 4,
 4,
 4,
 3,
 3,
 2,
 1,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 0,
 4,
 4,
 4,
 3,
 3,
 1,
 0,
 4,
 3,
 3,
 3,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 4,
 4,
 4,
 1,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 0,
 4,
 2,
 0,
 0,
 0,
 4,
 4,
 4,
 4,
 1,
 3,
 1,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 3,
 3,
 1,
 4,
 4,
 1,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 0,
 3,
 3,
 0,
 0,
 0,
 0,
 3,
 1,
 0,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 4,
 4,
 3,
 3,
 3,
 1,
 0,
 4,
 4,
 3,
 1,
 0,
 4,
 4,
 4,
 4,
 3,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 2,
 1,
 3,
 1,
 0,
 3,
 3,
 1,
 3,
 1,
 0,
 4,
 4,
 4,
 4,
 1,
 0,
 4,
 4,
 3,
 3,
 1,
 1,
 4,
 4,
 4,
 4,
 3,
 1,
 4,
 4,
 3,
 3,
 1,
 0,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 0,
 4,
 4,
 3,
 3,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 0,
 4,
 4,
 3,
 3,
 1,
 0,
 4,
 4,
 4,
 4,
 3,
 3,
 0,
 4,
 4,
 3,
 1,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 0,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 0,
 4,
 4,
 3,
 3,
 1,
 0,
 4,
 4,
 4,
 4,
 3,
 1,
 0,
 4,
 4,
 3,
 3,
 0,
 4,
 4,
 4,
 4,
 3,
 2,
 2,
 2,
 1,
 1,
 3,
 3,
 1,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 0,
 0,
 4,
 4,
 4,
 4,
 1,
 0,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 0,
 4,
 4,
 4,
 4,
 3,
 1,
 0,
 4,
 4,
 3,
 3,
 1,
 1,
 0,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 3,
 3,
 0,
 0,
 0,
 0,
 0,
 4,
 4,
 4,
 4,
 3,
 3,
 4,
 3,
 3,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 4,
 1,
 1,
 1,
 4,
 4,
 4,
 ...]

In [51]:
df['时段'] = period
df

,学工号,交易额,商户名称,交易日期,星期,是否为工作日,气温,气象站大气压,海平面大气压,相对湿度,平均风速,交易时间,时段
0,2021****86,8.90,淘乐学苑水果,2023/4/25,2,1,7,742.7,755.4,66,10,18:02,3
1,2021****86,11.84,美食林小猪憨尼麻辣烫,2023/4/25,2,1,7,742.7,755.4,66,10,17:35,3
2,2021****86,13.00,美食林川蜀源烤鱼,2023/4/25,2,1,7,742.7,755.4,66,10,11:46,1
3,2021****86,2.65,学苑食堂副食一组,2023/4/25,2,1,7,742.7,755.4,66,10,7:49,0
4,2021****86,18.40,紫丁香餐吧机器人收银组,2023/4/24,1,1,14,754.0,766.6,14,7,17:57,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1391,2021****86,14.00,民族二餐厅自助榆林镇筋饼,2022/1/1,6,0,-17,753.2,767.3,60,4,11:22,1
1392,2021****86,0.19,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:04,4
1393,2021****86,0.17,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:04,4
1394,2021****86,0.09,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:03,4
1395,2021****86,0.01,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:03,4

In [52]:
df.to_csv('D:/Innovation/DataSet/混合数据.csv',sep= ',', encoding='gbk')

In [61]:
def join_feature(feature):
    result = []
    for date_i in df["交易日期"]:
        for date_j in clm['date']:
            if date_i == date_j:
                temp = clm[clm['date'] == date_i]
                if temp[feature].isnull().any():
                    result.append(0)
                else:
                    result.append(1)
    return result

In [59]:
clm = load_data('clm.csv')
clm

     气温  气象站大气压  海平面大气压  相对湿度  平均风速        特殊天象 重要天象     时间       date
0    17   746.7   759.0    42     5         NaN  NaN  12:00   2023/5/1
1     6   739.6   752.3   100     3  轻度（小）（弱） 雨  NaN  12:00  2023/4/30
2    12   740.7   753.1    77     5         NaN  NaN  12:00  2023/4/29
3    11   745.1   757.7    94     4          轻雾  NaN  12:00  2023/4/28
4    19   743.2   755.4    32     8         NaN  NaN  12:00  2023/4/27
..   ..     ...     ...   ...   ...         ...  ...    ...        ...
481 -15   756.4   770.4    60     3         NaN  NaN  12:00   2022/1/5
482 -16   759.3   773.4    55     2         NaN  NaN  12:00   2022/1/4
483 -13   749.7   763.5    61     3         NaN  NaN  12:00   2022/1/3
484 -13   751.9   765.8    56     6         NaN  NaN  12:00   2022/1/2
485 -17   753.2   767.3    60     4         NaN  NaN  12:00   2022/1/1

[486 rows x 9 columns]

In [62]:
S = join_feature("特殊天象")
S

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 ...]

In [63]:
df['天气好/坏'] = S
df

,学工号,交易额,商户名称,交易日期,星期,是否为工作日,气温,气象站大气压,海平面大气压,相对湿度,平均风速,交易时间,时段,天气好/坏
0,2021****86,8.90,淘乐学苑水果,2023/4/25,2,1,7,742.7,755.4,66,10,18:02,3,0
1,2021****86,11.84,美食林小猪憨尼麻辣烫,2023/4/25,2,1,7,742.7,755.4,66,10,17:35,3,0
2,2021****86,13.00,美食林川蜀源烤鱼,2023/4/25,2,1,7,742.7,755.4,66,10,11:46,1,0
3,2021****86,2.65,学苑食堂副食一组,2023/4/25,2,1,7,742.7,755.4,66,10,7:49,0,0
4,2021****86,18.40,紫丁香餐吧机器人收银组,2023/4/24,1,1,14,754.0,766.6,14,7,17:57,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1391,2021****86,14.00,民族二餐厅自助榆林镇筋饼,2022/1/1,6,0,-17,753.2,767.3,60,4,11:22,1,0
1392,2021****86,0.19,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:04,4,0
1393,2021****86,0.17,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:04,4,0
1394,2021****86,0.09,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:03,4,0
1395,2021****86,0.01,B02公寓浴池,2022/1/1,6,0,-17,753.2,767.3,60,4,2:03,4,0

In [65]:
df.to_csv('D:/Innovation/DataSet/lai_temp.csv',sep= ',', encoding='gbk')